### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by sv2dev** [KevCJones/plugin-scss#14]
I use this plugin in my project https://github.com/flaviait/ng2-jspm-template and it worked perfectly well together with jspm version 0.17-beta.13 and 0.17-beta.14.
Howerver, a few days ago I start to get an error when running `jspm bundle` which seems to be related to this plugin:

```
err  TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.dirname (path.js:1324:5)
      at [project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6645:38
      at [project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6661:24
      at Array.map (native)
      at OptionManager.resolvePresets ([project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6650:22)
      at OptionManager.mergePresets ([project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6640:12)
      at OptionManager.mergeOptions ([project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6616:16)
      at OptionManager.init ([project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6732:12)
      at File.initOptions ([project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7375:77)
      at new File ([project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7319:24)
      at Pipeline.transform ([project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:3923:18)
      at [project-root]/jspm_packages/npm/systemjs-plugin-babel@0.0.9/plugin-babel.js:154:24
  Error loading [project-root]/jspm_packages/github/KevCJones/plugin-scss@0.2.11/index.js
```

This error seems to occur only on some machines. For example it occurs on my private machine (Arch Linux with nvm) and on a colleague's machine (Ubuntu) but it works on my machine at work (Linux Mint) and on the travis build.

When compiling inside the browser it still works.

**Comment by sv2dev** [comment]
Duplicate of https://github.com/jspm/jspm-cli/issues/1764
